[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "spark-dagster-taxi-pipeline"
version = "0.1.0"
description = "Local-first batch analytics pipeline using Dagster, PySpark, Postgres, and Parquet."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster==1.13.15",
    "psycopg[binary]==3.3.4",
    "pyspark==3.5.1"
]

[project.optional-dependencies]
dev = [
    "dagster-dg-cli==1.13.15",
    "dagster-webserver==1.13.15",
    "pytest==8.3.4",
    "ruff==0.8.6"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 130
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B"
]


[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "taxi_pipeline"
code_location_target_module = "taxi_pipeline.definitions"